### ISSUE TITLE
Absolute path import is not valid file URL path on Windows

### ISSUE THREAD

**Issue by filipditrich** [petrzjunior/barrelgun#1]
Running barrelgun shoot on Windows throws the following error:

```
pnpm barrelgun shoot -c barrelgun.config.js

Reading config from D:\Web_Design\Work\nfctron-account\barrelgun.config.js
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'
    at new NodeError (node:internal/errors:371:5)
    at defaultResolve (node:internal/modules/esm/resolve:1016:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:422:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:222:40)
    at ESMLoader.import (node:internal/modules/esm/loader:276:22)
    at importModuleDynamically (node:internal/modules/esm/translators:111:35)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)
    at loadConfig (file:///D:/Web_Design/Work/nfctron-account/node_modules/.pnpm/barrelgun@1.2.0/node_modules/barrelgun/dist/main.mjs:79:19)
    at shoot (file:///D:/Web_Design/Work/nfctron-account/node_modules/.pnpm/barrelgun@1.2.0/node_modules/barrelgun/dist/main.mjs:84:24)
    at Command.<anonymous> (file:///D:/Web_Design/Work/nfctron-account/node_modules/.pnpm/barrelgun@1.2.0/node_modules/barrelgun/dist/main.mjs:90:122) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}
 ELIFECYCLE  Command failed with exit code 1.
```

The problematic code:

https://github.com/petrzjunior/barrelgun/blob/d3a13e7be39e44c275d854397095e3e56e4950e0/src/shoot.ts#L11

Probable solution:
```js
 const promise = await import(pathToFileURL(absolutePath).toString()); 
```

**Comment by petrzjunior** [comment]
Fixed in 6b90e9ef0029fb555889fc283aefbc1455a8ac6b.
Thank you!
